[config]
skip_core_tasks = true

[env]
# @makerz = "caller"
INVOCATION_DIR = "."

[tasks.verify-cwd]
script_runner = "@duckscript"
script = '''
cd ${ISOLATED}
cd ${INVOCATION_DIR}
exec --fail-on-error sh -c "cat marker.test 1>&2"
'''
