[config]
skip_core_tasks = true

[env]
# @makerz = "caller"
INVOCATION_DIR = "."

[tasks.verify-cwd]
script_runner = "@duckscript"
script = '''
cd ${ISOLATED}
cd ${INVOCATION_DIR}
cat marker.test
'''
